# Generated by Django 5.1.6 on 2025-04-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(max_length=10),
        ),
    ]
