# Generated by Django 5.2 on 2025-04-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
