# Generated by Django 5.1.6 on 2025-04-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
