# Generated by Django 5.1.6 on 2025-04-30 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_listitem_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="first_name",
            new_name="name",
        ),
    ]
