# Generated by Django 5.1.5 on 2025-02-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.TextField()),
                ("lastName", models.TextField()),
                ("city", models.TextField()),
                ("email", models.TextField()),
                ("image", models.ImageField()),
            ],
        ),
    ]
