# Generated by Django 5.1.6 on 2025-04-01 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mini_fb", "0002_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
    ]
