# Generated by Django 5.1.6 on 2025-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_fb", "0005_rename_profile_image_profile_fk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="status_images/"),
        ),
    ]
